name: Test IPython beamline profiles
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  testing_beamline_profiles:
    name: Test profile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove BSStudio dependency for CI only
        run: |
          echo "Removing BSStudio dependency from pixi.toml"
          grep -n -A5 -B2 "bsstudio" pixi.toml || true
          sed -i '/^bsstudio = /d' pixi.toml
          echo "after removing BSStudio dependency from pixi.toml"
          grep -n -A5 -B2 "bsstudio" pixi.toml || true

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347  # v0.10.2
        with:
          pixi-version: v0.71.3
          cache: false
          environments : test
          frozen: true

      - name: Run pytest
        run: pixi run tests
