name: Test IPython beamline profiles
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  testing_beamline_profiles:
    name: Test profile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove BSStudio dependency for CI only
        run: |
          sed -i '/^bsstudio = { path = "\/home\/xf21id1\/git\/bsstudio"/d' pixi.toml
          grep -n "bsstudio" pixi.toml || echo "bsstudio not found"

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7  # v0.9.3
        with:
          pixi-version: v0.68.0
          run-install: false
          cache: false

      - name: Run pytest
        run: pixi run tests
